# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self.Betsy_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread
import sys
from CtxtGui import Ui_Form
apps = QtWidgets.QApplication(sys.argv)

class BetsyGUI(object):
    
    def __init__(self):
        self.app = apps
        self.Betsy = QtWidgets.QMainWindow()
        self.Betsy.setSizeIncrement(QtCore.QSize(1, 0))
        self.worker_thread = QThread()
        self.ctxgui =Ui_Form()

        self.Betsy.setObjectName("Betsy")
        self.Betsy.resize(914, 750)
        font = QtGui.QFont()
        font.setFamily("Hiragino Kaku Gothic Pro")
        self.Betsy.setFont(font)
        self.Betsy.setToolTipDuration(4)
        self.Betsy.setDocumentMode(True)
        self.Betsy.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(self.Betsy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatlog = QtWidgets.QTextEdit(self.widget)
        self.chatlog.setObjectName("chatlog")
        self.verticalLayout.addWidget(self.chatlog)
        spacerItem = QtWidgets.QSpacerItem(34, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")

        self.transcript = QtWidgets.QPushButton(self.widget_3)
        self.transcript.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BetsyApp/Images/icons/icons/png/24/music/sound-wave@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transcript.setIcon(icon)
        self.transcript.setIconSize(QtCore.QSize(30, 30))
        self.transcript.setFlat(True)
        self.transcript.setObjectName("transcript")
        self.gridLayout.addWidget(self.transcript, 1, 1, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.widget_3)
        self.sendButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("BetsyApp/Images/pngwing.com (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon1)
        self.sendButton.setIconSize(QtCore.QSize(30, 30))
        self.sendButton.setFlat(True)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 0, 1, 1, 1)
        self.userentry = QtWidgets.QTextEdit(self.widget_3)
        self.userentry.setObjectName("userentry")
        self.gridLayout.addWidget(self.userentry, 0, 0, 2, 1)
        self.Duration_label = QtWidgets.QLabel(self.widget_3)
        self.Duration_label.setMaximumSize(QtCore.QSize(267, 152))
        self.Duration_label.setStyleSheet("QLabel {\n"
"  border-radius: 20px;\n"
"  background-color: green;\n"
"  color: #000000;\n"
"  padding: 5px;\n"
"}")
        self.Duration_label.setObjectName("Duration_label")
        self.gridLayout.addWidget(self.Duration_label, 2, 1, 2, 2)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.systementry = QtWidgets.QTextEdit(self.widget_2)
        self.systementry.setMaximumSize(QtCore.QSize(16777215, 122))
        self.systementry.setObjectName("systementry")
        self.verticalLayout_2.addWidget(self.systementry)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.applyButton = QtWidgets.QPushButton(self.widget_2)
        self.applyButton.setMaximumSize(QtCore.QSize(167, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.applyButton.setFont(font)
        self.applyButton.setStyleSheet("QPushButton {\n"
"  background-color: #008000;\n"
"  border-radius: 5px;\n"
"  border: none;\n"
"  color: black;\n"
"  padding: 10px 16px;\n"
"  font-size: 14px;\n"
"  font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #1565C0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #0D47A1;\n"
"}")
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout_2.addWidget(self.applyButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tokenlabel = QtWidgets.QLabel(self.widget_2)
        self.tokenlabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tokenlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tokenlabel.setObjectName("tokenlabel")
        self.verticalLayout_2.addWidget(self.tokenlabel)
        self.tokendisplay = QtWidgets.QLCDNumber(self.widget_2)
        self.tokendisplay.setMaximumSize(QtCore.QSize(170, 40))
        self.tokendisplay.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tokendisplay.setStyleSheet("border radius : 20 px;")
        self.tokendisplay.setObjectName("tokendisplay")
        self.verticalLayout_2.addWidget(self.tokendisplay)
        self.tokenSlider = QtWidgets.QSlider(self.widget_2)
        self.tokenSlider.setMaximumSize(QtCore.QSize(167, 16777215))
        self.tokenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tokenSlider.setObjectName("tokenSlider")
        
        self.verticalLayout_2.addWidget(self.tokenSlider)
        self.templabel = QtWidgets.QLabel(self.widget_2)
        self.templabel.setAlignment(QtCore.Qt.AlignCenter)
        self.templabel.setObjectName("templabel")
        self.verticalLayout_2.addWidget(self.templabel)
        self.tempdisplay = QtWidgets.QLCDNumber(self.widget_2)
        self.tokendisplay.setStyleSheet('''
    QLCDNumber {
        background-color: black;
        color: green;
        border: 2px solid green;
        border-radius: 5px;
    }

    QLCDNumber::number {
        font-size: 30px;
        font-family: Arial;
    }
''')
        self.tempdisplay.setStyleSheet('''
    QLCDNumber {
        background-color: black;
        color: green;
        border: 2px solid green;
        border-radius: 5px;
    }

    QLCDNumber::number {
        font-size: 30px;
        font-family: Arial;
    }
''')
        self.tempdisplay.setMaximumSize(QtCore.QSize(167, 40))
        self.tempdisplay.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tempdisplay.setObjectName("tempdisplay")
        self.verticalLayout_2.addWidget(self.tempdisplay)
        self.tempSlider = QtWidgets.QSlider(self.widget_2)
        self.tempSlider.setMaximumSize(QtCore.QSize(167, 16777215))
        self.tempSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tempSlider.setObjectName("tempSlider")
        self.tokenSlider.setMinimum(0)
        self.tokenSlider.setMaximum(2096)
        self.tempSlider.setMinimum(0)
        self.tempSlider.setMaximum(1000)
        self.tokenSlider.setStyleSheet('''
        QSlider {
            background-color: #2c3e50;
            border: none;
            height: 10px;
            margin: 0;
            padding: 0;
        }


        QSlider::groove:horizontal {
            background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #27ae60, stop:1 #2ecc71);
            border: none;
            height: 4px;
            margin: 0;
            padding: 0;
        }


        QSlider::handle:horizontal {
            background-color: #fff;
            border: 1px solid #2c3e50;
            border-radius: 10px;
            height: 20px;
            margin: -6px 0;
            width: 20px;
        }


        QSlider::handle:horizontal:hover {
            background-color: #ddd;
            border: 1px solid #27ae60;
        }


        QSlider::sub-page:horizontal {
            background: qlineargradient( x1:0, y1:0, x2:1, y2:1, stop:0 #27ae60, stop:1 #2ecc71);
            height: 4px;
        }


        QSlider::add-page:horizontal {
            background: #fff;
            border: none;
            height: 4px;
        }


        QSlider::handle:horizontal:pressed {
            background-color: #27ae60;
            border: 1px solid #27ae60;
        }''')
        
        self.tempSlider.setStyleSheet('''
        QSlider {
            background-color: #2c3e50;
            border: none;
            height: 10px;
            margin: 0;
            padding: 0;
        }


        QSlider::groove:horizontal {
            background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #27ae60, stop:1 #2ecc71);
            border: none;
            height: 4px;
            margin: 0;
            padding: 0;
        }


        QSlider::handle:horizontal {
            background-color: #fff;
            border: 1px solid #2c3e50;
            border-radius: 10px;
            height: 20px;
            margin: -6px 0;
            width: 20px;
        }


        QSlider::handle:horizontal:hover {
            background-color: #ddd;
            border: 1px solid #27ae60;
        }


        QSlider::sub-page:horizontal {
            background: qlineargradient( x1:0, y1:0, x2:1, y2:1, stop:0 #27ae60, stop:1 #2ecc71);
            height: 4px;
        }


        QSlider::add-page:horizontal {
            background: #fff;
            border: none;
            height: 4px;
        }


        QSlider::handle:horizontal:pressed {
            background-color: #27ae60;
            border: 1px solid #27ae60;
        }''')
        self.tokenSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tokenSlider.valueChanged.connect(self.tokendisplay.display)
        self.tempSlider.valueChanged.connect(self.tempdisplay.display)
        self.temp_sliderValue=0
        self.token_sliderValue=0
        self.tempSlider.valueChanged.connect(self.sliderMoved)
        self.tokenSlider.valueChanged.connect(self.sliderMoved)
        
        
        self.verticalLayout_2.addWidget(self.tempSlider)
        self.accuratebox = QtWidgets.QTextEdit(self.widget_2)
        self.accuratebox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.accuratebox.setObjectName("accuratebox")
        self.verticalLayout_2.addWidget(self.accuratebox)
        self.horizontalLayout.addWidget(self.widget_2)
        self.Betsy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.Betsy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuContextes = QtWidgets.QMenu(self.menubar)
        self.menuContextes.setObjectName("menuContextes")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        self.Betsy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.Betsy)
        self.statusbar.setObjectName("statusbar")
        self.Betsy.setStatusBar(self.statusbar)
        self.actionNouvelle_seance_de_travail = QtWidgets.QAction(self.Betsy)
        self.actionNouvelle_seance_de_travail.setObjectName("actionNouvelle_seance_de_travail")
        self.actionEnregistrer_le_seane_de_travail = QtWidgets.QAction(self.Betsy)
        self.actionEnregistrer_le_seane_de_travail.setObjectName("actionEnregistrer_le_seane_de_travail")
        self.actionCreer_un_nouveau_contexte = QtWidgets.QAction(self.Betsy)
        self.actionCreer_un_nouveau_contexte.setObjectName("actionCreer_un_nouveau_contexte")
        self.actionDocumentation = QtWidgets.QAction(self.Betsy)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSoutenir_le_projet = QtWidgets.QAction(self.Betsy)
        self.actionSoutenir_le_projet.setObjectName("actionSoutenir_le_projet")
        self.actionQuitter = QtWidgets.QAction(self.Betsy)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionSupprimer_un_contexte = QtWidgets.QAction(self.Betsy)
        self.actionSupprimer_un_contexte.setObjectName("actionSupprimer_un_contexte")
        self.menuFichier.addAction(self.actionNouvelle_seance_de_travail)
        self.menuFichier.addAction(self.actionEnregistrer_le_seane_de_travail)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuContextes.addAction(self.actionCreer_un_nouveau_contexte)
        self.menuContextes.addAction(self.actionSupprimer_un_contexte)
        self.menuAide.addAction(self.actionDocumentation)
        self.menuAide.addAction(self.actionSoutenir_le_projet)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuContextes.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.Betsy)
    
    def sliderMoved(self):
        # Récupérer la valeur du slider
        temp_value = self.tempSlider.value()
        token_value =self.tokenSlider.value()

        # Stocker la valeur dans une variable
        self.temp_sliderValue = temp_value
        self.token_sliderValue = token_value

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Betsy.setWindowTitle(_translate("self.Betsy", "Betsy"))
        self.chatlog.setToolTip(_translate("self.Betsy", "Chatlog"))
        self.transcript.setToolTip(_translate("self.Betsy", "Message Vocal"))
        self.sendButton.setToolTip(_translate("self.Betsy", "Envoyer"))
        self.Duration_label.setToolTip(_translate("self.Betsy", "Durrée max 30 seconde"))
        self.Duration_label.setText(_translate("self.Betsy","Transcription"))
        self.applyButton.setToolTip(_translate("self.Betsy", "Initialisation de l\'IA"))
        self.applyButton.setText(_translate("self.Betsy", "Initialiser"))
        self.tokenlabel.setText(_translate("self.Betsy", "Token"))
        self.templabel.setText(_translate("self.Betsy", "Temp"))
        self.menuFichier.setTitle(_translate("self.Betsy", "Assistant"))
        self.menuContextes.setTitle(_translate("self.Betsy", "Contextes"))
        self.menuAide.setTitle(_translate("self.Betsy", "Aide"))
        self.actionNouvelle_seance_de_travail.setText(_translate("self.Betsy", "Nouvelle seance de travail"))
        self.actionEnregistrer_le_seane_de_travail.setText(_translate("self.Betsy", "Enregistrer le seane de travail"))
        self.actionCreer_un_nouveau_contexte.setText(_translate("self.Betsy", "Creer un nouveau contexte"))
        self.actionDocumentation.setText(_translate("self.Betsy", "Documentation "))
        self.actionSoutenir_le_projet.setText(_translate("self.Betsy", "Soutenir le projet"))
        self.actionQuitter.setText(_translate("self.Betsy", "Quitter"))
        self.actionSupprimer_un_contexte.setText(_translate("self.Betsy", "Supprimer un contexte"))
    
    def startApp(self):
        self.Betsy.show()
        self.userentry.moveToThread(self.worker_thread)
        sys.exit(self.app.exec_())
