# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreatecontextdefineGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(940, 689)
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(80, 170, 291, 361))
        self.widget_8.setObjectName("widget_8")
        self.groupBox = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 251, 341))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 231, 79))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 140, 231, 79))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 240, 231, 79))
        self.textEdit_3.setObjectName("textEdit_3")
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setGeometry(QtCore.QRect(160, 10, 561, 141))
        self.widget_9.setObjectName("widget_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 60, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 381, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 30, 341, 79))
        self.textEdit_7.setObjectName("textEdit_7")
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setGeometry(QtCore.QRect(200, 560, 541, 81))
        self.widget_10.setObjectName("widget_10")
        self.pushButton = QtWidgets.QPushButton(self.widget_10)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 201, 61))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.widget_11 = QtWidgets.QWidget(Form)
        self.widget_11.setGeometry(QtCore.QRect(570, 170, 291, 361))
        self.widget_11.setObjectName("widget_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 251, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 40, 231, 79))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 140, 231, 79))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 240, 231, 79))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(760, 20, 141, 111))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 141, 111))
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(381, 221, 201, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(30, 20, 30, 20)
        self.gridLayout.setVerticalSpacing(85)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.groupBox_3.setTitle(_translate("Form", "GroupBox"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
